[build-system]
requires= ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "PlayWithVenv"
version = "0.0.1"
requires-python = ">=3.8"

[project.scripts]
pwv = "PlayWithVenv.__main__:main"

[tool.setuptool.packages.find]
where = ["."]