[build-system]
requires= ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "PlayWithVenv"
version = "0.0.1"

[project.scripts]]
pwv = "PlayWithVenv.__main__:main

[tool.setuptools.packages.find]
where = ["."]